services:
    _defaults:
        public: true
        autowire: true
    sebk_small_orm_connections:
        class: Sebk\SmallOrmCore\Factory\Connections
        arguments: ["%sebk_small_orm.connexions%", "%sebk_small_orm.default_connection%"]
    sebk_small_orm_dao:
        class: Sebk\SmallOrmCore\Factory\Dao
        autowire: true
        arguments: ["@sebk_small_orm_connections", "%sebk_small_orm.bundles%", "@service_container"]
    sebk_small_orm_validator:
        class: Sebk\SmallOrmCore\Factory\Validator
        arguments: ["@sebk_small_orm_dao", "%sebk_small_orm.bundles%"]
    sebk_small_orm_generator:
        class: Sebk\SmallOrmCore\Generator\DaoGenerator
        arguments: ["@sebk_small_orm_dao", "@sebk_small_orm_connections", "@service_container", "%sebk_small_orm.bundles%"]
    sebk_small_orm_layers:
        class: Sebk\SmallOrmCore\Layers\Layers
        arguments: ["@sebk_small_orm_connections", "%sebk_small_orm.bundles%", "@service_container"]
    # Autowire aliases
    Sebk\SmallOrmCore\Factory\Dao:
        alias: "sebk_small_orm_dao"
    Sebk\SmallOrmCore\Factory\Connections:
        alias: "sebk_small_orm_connections"
    Sebk\SmallOrmCore\Factory\Validator:
        alias: "sebk_small_orm_validator"
    # Commands
    Sebk\SmallOrmBundle\Command\Generate\DaoCommand:
        public: true
        arguments: ["%sebk_small_orm.bundles%", "@sebk_small_orm_connections", "@sebk_small_orm_generator", "@service_container"]
        tags: [console.command]
    Sebk\SmallOrmBundle\Command\LayersExecuteCommand:
        public: true
        arguments: ["@sebk_small_orm_layers"]
        tags: [console.command]
    Sebk\SmallOrmBundle\Command\UpdateDaoCommand:
        public: true
        arguments: ["@service_container"]
        tags: [console.command]
    Sebk\SmallOrmBundle\Command\Generate\ModelAutocompletionCommand:
        public: true
        arguments: ["@service_container"]
        tags: [console.command]